name: try-workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: checkC
      run: |
        cd /d C:\
        dir
      
      
