name: launc-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-launch-tests:

    runs-on: windows-latest
    steps:
    - name: Check ml64.exe
      run: |
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.25.28610\bin\Hostx64\x64"
        dir
        env
    - name: Set PATH to ml64.exe
      run: echo "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.25.28610\bin\Hostx64\x64" >> $GITHUB_PATH
    - name: Check PATH
      run: echo $GITHUB_PATH
    - name: Clone repository
      uses: actions/checkout@main
    - name: Build tests
      run: |
        mkdir obj
        make build_tests ASMC="ml64.exe"
    - name: Launch tests
      run: ./tests.exe
      
      
