name: launc-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-launch-tests:

    runs-on: windows-latest
    steps:
    - name: Check ml64.exe
      run: |
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.25.28610\bin\Hostx64\x64"
        dir
    - name: Set PATH to ml64.exe
      run:  echo "—Å:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.25.28610\bin\Hostx64\x64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: Check PATH
      run: env
    - name: Clone repository
      uses: actions/checkout@main
    - name: Build tests
      run: |
        mkdir obj
        make build_tests
    - name: Launch tests
      run: ./tests.exe
      
      
