name: launc-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-launch-tests:

    runs-on: windows-latest
    steps:
    - name: Set PATH to ml64.exe
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      run: |
        echo "::add-path::C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\bin\Hostx64\x64"
        dir
    - name: Clone repository
      uses: actions/checkout@main
    - name: Build tests
      run: make build_tests
    - name: Launch tests
      run: ./tests.exe
      
      
