name: test_when_push_to_main
on:
  push:
    branches: [main]

jobs:
  test_program:
    runs-on: windows-latest
    steps:
      #- name: Clone repository to docker
      #  uses: actions/checkout@main
      #- name: Build tests
      #  run: make build_tests
      - name: Show files
        run: |
          cd D:\a
          dir
      #- name: Run tests
      #  run: tests.exe
